// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI0y9iq4MAJqAYpiaw635PAltp5UHCTbw',
    appId: '1:986467662316:web:c4a3c9206d42ed48f5a8c9',
    messagingSenderId: '986467662316',
    projectId: 'hello-farmer-34770',
    authDomain: 'hello-farmer-34770.firebaseapp.com',
    storageBucket: 'hello-farmer-34770.firebasestorage.app',
    measurementId: 'G-41X8PW81SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62AeWkTsKDth0lUcfQvYs1inlRHzM-wI',
    appId: '1:986467662316:android:567ce1b4e9a2a5c4f5a8c9',
    messagingSenderId: '986467662316',
    projectId: 'hello-farmer-34770',
    storageBucket: 'hello-farmer-34770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpoU1xVap_56IT1_N5MgNYv5pRi76atw',
    appId: '1:986467662316:ios:b0671c597eafcf18f5a8c9',
    messagingSenderId: '986467662316',
    projectId: 'hello-farmer-34770',
    storageBucket: 'hello-farmer-34770.firebasestorage.app',
    iosBundleId: 'com.example.helloFarmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpoU1xVap_56IT1_N5MgNYv5pRi76atw',
    appId: '1:986467662316:ios:b0671c597eafcf18f5a8c9',
    messagingSenderId: '986467662316',
    projectId: 'hello-farmer-34770',
    storageBucket: 'hello-farmer-34770.firebasestorage.app',
    iosBundleId: 'com.example.helloFarmer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI0y9iq4MAJqAYpiaw635PAltp5UHCTbw',
    appId: '1:986467662316:web:caf29e4bb00f7ef7f5a8c9',
    messagingSenderId: '986467662316',
    projectId: 'hello-farmer-34770',
    authDomain: 'hello-farmer-34770.firebaseapp.com',
    storageBucket: 'hello-farmer-34770.firebasestorage.app',
    measurementId: 'G-Y588TYQ8J1',
  );
}
